import fetch from '$pc/utils/fetch';

export default {
    // 获取全局的配置信息,
    GetBaseConfig: params => fetch(`/base/getBaseConfig`, params, {}),
    // 获取省份数据,
    GetProvinceData: params => fetch(`/base/getProvinceData`, params, { cache: true }),
    // 获取市区数据,
    GetSubRegionData: params => fetch(`/base/getSubRegionData`, params, {}),
    // 获取市县数据,
    GetRegionData: params => fetch(`/base/getRegionData`, params, {}),
    // 获取政区列表,
    GetAdcdCity: params => fetch(`/base/waring/adcdCity`, params, {}),
    // 获取当前客户端的地理位置信息,
    GetGeographicInfo: params => fetch(`/base/getGeographicInfo`, params, {}),
    // 查询所有的app,
    GetAppAll: params => fetch(`/app/appAll`, params, {}),
    // 获取当前账号的菜单列表,从session中获取,
    GetMenuListForUser: params => fetch(`/menu/menuListForUser`, params, {}),
    // 获取项目中能使用的菜单列表,
    GetMenuListForAvailable: params => fetch(`/menu/menuLForAvailable`, params, {}),
    // 获取导航菜单的详细信息,
    GetMenuInfo: params => fetch(`/menu/menuInfo`, params, {}),
    // 新增菜单项,
    AddMenu: params => fetch(`/menu/addMenu`, params, { fullLoading: true, successTips: true }),
    // 修改菜单项,
    UpdateMenu: params => fetch(`/menu/updateMenu`, params, { fullLoading: true, successTips: true }),
    // 删除菜单项,
    DeleteMenu: params => fetch(`/menu/deleteMenu`, params, { fullLoading: true, successTips: true }),
    // 获取当前平台的菜单列表,
    GetMenuListForApp: params => fetch(`/menu/menuListForApp`, params, {}),
    // 获取当前平台的某个角色的菜单列表,
    GetMenuListForAppAndRole: params => fetch(`/menu/menuListForAppAndRole`, params, {}),
    // 保存当前平台的某个角色的菜单列表,
    SetMenuListForAppAndRole: params => fetch(`/menu/saveMenuListForAppAndRole`, params, { fullLoading: true, successTips: true }),
    // 新增账号,
    AddUser: params => fetch(`/user/addUser`, params, { fullLoading: true, successTips: true }),
    // 删除账号,
    DeleteUser: params => fetch(`/user/deleteUser`, params, { fullLoading: true, successTips: true }),
    // 修改账号,
    UpdateUser: params => fetch(`/user/updateUser`, params, { fullLoading: true, successTips: true }),
    // 获取账号信息,
    GetUser: params => fetch(`/user/getUser`, params, {}),
    // 获取用户列表,
    GetUserAll: params => fetch(`/user/getUserAll`, params, {}),
    // 账户激活,
    SetUserActive: params => fetch(`/user/setUserActive`, params, { fullLoading: true, successTips: true }),
    // 账户锁定,
    SetUserLock: params => fetch(`/user/setUserLock`, params, { fullLoading: true, successTips: true }),
    // 账户锁定,
    SetUserUnLock: params => fetch(`/user/setUserUnLock`, params, { fullLoading: true, successTips: true }),
    // 重置密码,
    ResetPassword: params => fetch(`/user/resetPassword`, params, { fullLoading: true, successTips: true }),
    // 获取用户的分组信息,
    GetUserDepts: params => fetch(`/user/getUserDepts`, params, {}),
    // 设置用户的分组信息,
    SetUserDepts: params => fetch(`/user/setUserDepts`, params, { fullLoading: true, successTips: true }),
    // 修改密码,
    UpdatePassword: params => fetch(`/user/updatePassword`, params, { fullLoading: true, successTips: true }),
    // 保存上传的用户文件,
    ImportSaveUser: params => fetch(`/user/importSaveUser`, params, { fullLoading: true, successTips: true }),
    // 修改用户的页面布局信息,
    UpdateLayout: params => fetch(`/user/updateLayout`, params, {}),
    // 登录,
    Login: params => fetch(`/login/login`, params, {}),
    // 登出,
    SignOut: params => fetch(`/login/signOut`, params, {})
};
