import fetch from '@rich/richwayweb-components/src/pc/utils/fetch';

export default {
    // 获取全局的配置信息,
    GetBaseConfig: params => fetch(`/base/getBaseConfig`, params, {}),
    // 获取省份数据,
    GetProvinceData: params => fetch(`/base/getProvinceData`, params, {"cache":true}),
    // 获取市区数据,
    GetSubRegionData: params => fetch(`/base/getSubRegionData`, params, {}),
    // 获取市县数据,
    GetRegionData: params => fetch(`/base/getRegionData`, params, {}),
    // 获取政区列表,
    GetAdcdCity: params => fetch(`/base/waring/adcdCity`, params, {}),
    // 获取当前客户端的地理位置信息,
    GetGeographicInfo: params => fetch(`/base/getGeographicInfo`, params, {}),
    // 查询所有的app,
    GetAppAll: params => fetch(`/app/appAll`, params, {}),
    // 获取当前账号的菜单列表,从session中获取,
    GetMenuListForUser: params => fetch(`/menu/menuListForUser`, params, {}),
    // 获取项目中能使用的菜单列表,
    GetMenuListForAvailable: params => fetch(`/menu/menuLForAvailable`, params, {}),
    // 获取导航菜单的详细信息,
    GetMenuInfo: params => fetch(`/menu/menuInfo`, params, {}),
    // 新增菜单项,
    AddMenu: params => fetch(`/menu/addMenu`, params, {"fullLoading":true,"successTips":true}),
    // 修改菜单项,
    UpdateMenu: params => fetch(`/menu/updateMenu`, params, {"fullLoading":true,"successTips":true}),
    // 删除菜单项,
    DeleteMenu: params => fetch(`/menu/deleteMenu`, params, {"fullLoading":true,"successTips":true}),
    // 获取当前平台的菜单列表,
    GetMenuListForApp: params => fetch(`/menu/menuListForApp`, params, {}),
    // 获取当前平台的某个角色的菜单列表,
    GetMenuListForAppAndRole: params => fetch(`/menu/menuListForAppAndRole`, params, {}),
    // 保存当前平台的某个角色的菜单列表,
    SetMenuListForAppAndRole: params => fetch(`/menu/saveMenuListForAppAndRole`, params, {"fullLoading":true,"successTips":true}),
    // 新增账号,
    AddUser: params => fetch(`/user/addUser`, params, {"fullLoading":true,"successTips":true}),
    // 删除账号,
    DeleteUser: params => fetch(`/user/deleteUser`, params, {"fullLoading":true,"successTips":true}),
    // 修改账号,
    UpdateUser: params => fetch(`/user/updateUser`, params, {"fullLoading":true,"successTips":true}),
    // 获取账号信息,
    GetUser: params => fetch(`/user/getUser`, params, {}),
    // 获取用户列表,
    GetUserAll: params => fetch(`/user/getUserAll`, params, {}),
    // 账户激活,
    SetUserActive: params => fetch(`/user/setUserActive`, params, {"fullLoading":true,"successTips":true}),
    // 账户锁定,
    SetUserLock: params => fetch(`/user/setUserLock`, params, {"fullLoading":true,"successTips":true}),
    // 账户锁定,
    SetUserUnLock: params => fetch(`/user/setUserUnLock`, params, {"fullLoading":true,"successTips":true}),
    // 重置密码,
    ResetPassword: params => fetch(`/user/resetPassword`, params, {"fullLoading":true,"successTips":true}),
    // 获取用户的分组信息,
    GetUserDepts: params => fetch(`/user/getUserDepts`, params, {}),
    // 设置用户的分组信息,
    SetUserDepts: params => fetch(`/user/setUserDepts`, params, {"fullLoading":true,"successTips":true}),
    // 修改密码,
    UpdatePassword: params => fetch(`/user/updatePassword`, params, {"fullLoading":true,"successTips":true}),
    // 保存上传的用户文件,
    ImportSaveUser: params => fetch(`/user/importSaveUser`, params, {"fullLoading":true,"successTips":true}),
    // 修改用户的页面布局信息,
    UpdateLayout: params => fetch(`/user/updateLayout`, params, {}),
    // 登录,
    Login: params => fetch(`/login/login`, params, {}),
    // 登出,
    SignOut: params => fetch(`/login/signOut`, params, {}),
    // 值班安排页-值班人员信息列表,
    GetDutyList: params => fetch(`/duty/getDutyList`, params, {}),
    // 值班安排页-添加新值班人员成功,
    AddDuty: params => fetch(`/duty/addDuty`, params, {"fullLoading":true,"successTips":true}),
    // 值班安排页-编辑值班人员成功提示,
    UpdateDuty: params => fetch(`/duty/updateDuty`, params, {"fullLoading":true,"successTips":true}),
    // 值班安排页-删除值班人员信息,
    DeleteDuty: params => fetch(`/duty/deleteDuty`, params, {"fullLoading":true,"successTips":true}),
    // 值班安排页-添加弹框里面的时段请求,
    GetTimeInterval: params => fetch(`/duty/getTimeInterval`, params, {}),
    // 值班安排页-添加弹框里面的值班人员请求,
    GetDutyManagePersonRole: params => fetch(`/duty/getDutyManagePersonRole`, params, {}),
    // 值班安排页-获取编辑弹框里面值班人员的信息,
    GetDutyManagementPerson: params => fetch(`/duty/getDutyManagementPerson`, params, {}),
    // 值班安排页-下载值班导入模版,
    DownloadTemplate: params => fetch(`/duty/downloadTemplate`, params, {}),
    // 值班安排页-下载值班导入模版,
    ImportSchedulee: params => fetch(`/duty/importSchedulee`, params, {"fullLoading":true,"successTips":true}),
    // 获取所有值班人员信息,
    GetAllPerson: params => fetch(`/duty/getAllPerson`, params, {}),
    // 值班登记页-页面头部时间段信息,
    GetDutyTime: params => fetch(`/duty/getDutyTime`, params, {}),
    // 提交值班信息,
    AddRegister: params => fetch(`/duty/addRegister`, params, {"fullLoading":true,"successTips":true}),
    // 值班登记页-值班报告底部折叠版表格数据,
    GetDutyReportForm: params => fetch(`/duty/getDutyReportForm`, params, {}),
    // 值班登记页-值班报告的汛情表,
    GetFloodSeasonTable: params => fetch(`/duty/getFloodSeasonTable`, params, {}),
    // 值班登记页-值班报告的保存,
    GetReportReport: params => fetch(`/duty/getReportReport`, params, {"fullLoading":true,"successTips":true}),
    // 值班登记页-保存排班安排记录,
    AddDutyRecord: params => fetch(`/duty/addDutyRecord`, params, {"fullLoading":true,"successTips":true}),
    // 值班登记页-底部标签的删除,
    DeleteDutyRecord: params => fetch(`/duty/deleteDutyRecord`, params, {"fullLoading":true,"successTips":true}),
    // 获取值班登记页面的scheduleId,
    GetScheduleId: params => fetch(`/duty/getScheduleId`, params, {}),
    // 获取值班人员登记页面右侧日历下方的显示信息,
    GetDutyPersonnel: params => fetch(`/duty/getDutyPersonnel`, params, {}),
    // 获取值班人员登记页面右侧日历下方的显示信息2,
    GetDutyPersonnelInfo: params => fetch(`/duty/getDutyPersonnelInfo`, params, {}),
    // 值班记录页-获取值班记录列表,
    GetDutyRecordInfo: params => fetch(`/duty/getDutyRecordInfo`, params, {}),
    // 值班记录页-值班记录的详细记录（弹框里面的信息）,
    GetQueryDutyRecordDetails: params => fetch(`/duty/getQueryDutyRecordDetails`, params, {}),
    // 值班快报页-列表数据,
    GetDutyBulletinList: params => fetch(`/duty/getDutyBulletinList`, params, {}),
    // 值班快报页-提交添加的值班人员信息,
    ExpressSubmitInfo: params => fetch(`/duty/expressSubmitInfo`, params, {"fullLoading":true,"successTips":true}),
    // 值班快报页-点击删除,
    ExpressDeleteInfo: params => fetch(`/duty/expressDeleteInfo`, params, {"fullLoading":true,"successTips":true}),
    // 值班快报页-请求表格数据,
    GetFastReport: params => fetch(`/duty/getFastReport`, params, {}),
    // 值班快报页-新增保存,
    ReportSave: params => fetch(`/duty/reportSave`, params, {"fullLoading":true,"successTips":true}),
    // 值班快报页-删除,
    ReportDelete: params => fetch(`/duty/reportDelete`, params, {"fullLoading":true,"successTips":true}),
    // 值班快报页-echart请求,
    GetReportEchartInfo: params => fetch(`/duty/getReportEchartInfo`, params, {}),
    // 发送列表页-数据列表,
    GetSendList: params => fetch(`/communication/getSendList`, params, {}),
    // 发送列表页-数据列表,
    Reissue: params => fetch(`/communication/reissue`, params, {"fullLoading":true,"successTips":true}),
    // 发送列表页-数据列表,
    DeleteSMSList: params => fetch(`/communication/deleteSMSList`, params, {"fullLoading":true,"successTips":true}),
    // 发送列表页-点击状态，发送数据请求,
    SendListStateTableInfo: params => fetch(`/communication/sendListStateTableInfo`, params, {}),
    // 发送列表页-点击补发，发送数据请求,
    SendListStateReplacement: params => fetch(`/communication/sendListStateReplacement`, params, {"fullLoading":true,"successTips":true}),
    // 编辑短信页-左侧联系人列表,
    GetContactList: params => fetch(`/communication/getContactList`, params, {}),
    // 编辑短信页-左侧联系人防汛列表,
    GetFloodControlList: params => fetch(`/communication/getFloodControlList`, params, {}),
    // 编辑短信页-点击tree，显示穿梭宽的信息,
    GetcontactsList: params => fetch(`/communication/getcontactsList`, params, {}),
    // 编辑短信页-右侧头部信息发送签名方式,
    Gettypes: params => fetch(`/communication/gettypes`, params, {}),
    // 编辑短信页-点击确认发送,
    SendOut: params => fetch(`/communication/sendOut`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-联系人人数,
    GetCount: params => fetch(`/communication/getCount`, params, {}),
    // 通讯录页面-表格信息,
    GetContactTable: params => fetch(`/communication/getContactTable`, params, {}),
    // 通讯录页面-tree的添加成功提示,
    AddAContact: params => fetch(`/communication/addAContact`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-删除联系人信息,
    DeleteContact: params => fetch(`/communication/deleteContact`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-添加编辑联系人,
    AddEditContact: params => fetch(`/communication/addEditContact`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-成功删除一行tree,
    DeleteTreelist: params => fetch(`/communication/deleteTreelist`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-移动到组,
    CopyToGrp: params => fetch(`/communication/copyToGrp`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-移动到组,
    MoveToGrp: params => fetch(`/communication/moveToGrp`, params, {"fullLoading":true,"successTips":true}),
    // 通讯录页面-导入联系人,
    ImportContacts: params => fetch(`/communication/importContacts`, params, {"fullLoading":true,"successTips":true}),
    // 编辑短信页-左侧列表防汛联系人,
    PersonIncharge: params => fetch(`/communication/personIncharge`, params, {}),
    // 编辑短信页-组里面的防汛通讯人,
    PersonInchargeGroup: params => fetch(`/communication/personInchargeGroup`, params, {}),
    // 责任人维护页-危险区责任人-左边栏信息,
    GetDangerAdcddAnadTree: params => fetch(`/personLiableMaintenance/getDangerAdcddAnadTree`, params, {}),
    // 责任人维护页-危险区责任人-右边栏信息,
    GetDangerPersonList: params => fetch(`/personLiableMaintenance/getDangerPersonList`, params, {}),
    // 责任人维护页-危险区责任人-右侧保存按钮,
    GetDangerPersonsSave: params => fetch(`/personLiableMaintenance/getDangerPersonsSave`, params, {"fullLoading":true,"successTips":true}),
    // 责任人维护页-防汛责任人-左边栏信息,
    GetFloodPreventionTree: params => fetch(`/personLiableMaintenance/getFloodPreventionTree`, params, {}),
    // 自动预警人员-保存按钮,
    GetnotifiedPersonsSave: params => fetch(`/personLiableMaintenance/getnotifiedPersonsSave`, params, {"fullLoading":true,"successTips":true}),
    // 自动预警人员,
    GetAutomaticWarningTree: params => fetch(`/personLiableMaintenance/getAutomaticWarningTree`, params, {}),
    // 责任人维护页-导入excel表格,
    ImportImpperson: params => fetch(`/personLiableMaintenance/importImpperson`, params, {"fullLoading":true,"successTips":true})
};