import fetch from '@rich/richwayweb-components/src/pc/utils/fetch';

export default {
    // 获取全局的配置信息,
    GetBaseConfig: params => fetch(`/base/getBaseConfig`, params, {}),
    // 获取省份数据,
    GetProvinceData: params => fetch(`/base/getProvinceData`, params, {"cache":true}),
    // 获取市区数据,
    GetSubRegionData: params => fetch(`/base/getSubRegionData`, params, {}),
    // 获取市县数据,
    GetRegionData: params => fetch(`/base/getRegionData`, params, {}),
    // 获取政区列表,
    GetAdcdCity: params => fetch(`/base/waring/adcdCity`, params, {}),
    // 获取当前客户端的地理位置信息,
    GetGeographicInfo: params => fetch(`/base/getGeographicInfo`, params, {}),
    // 查询所有的app,
    GetAppAll: params => fetch(`/app/appAll`, params, {}),
    // 获取当前账号的菜单列表,从session中获取,
    GetMenuListForUser: params => fetch(`/menu/menuListForUser`, params, {}),
    // 获取项目中能使用的菜单列表,
    GetMenuListForAvailable: params => fetch(`/menu/menuLForAvailable`, params, {}),
    // 获取导航菜单的详细信息,
    GetMenuInfo: params => fetch(`/menu/menuInfo`, params, {}),
    // 保存菜单,
    SaveMenu: params => fetch(`/menu/saveMenu`, params, {"fullLoading":true,"successTips":true}),
    // 删除菜单,
    DeleteMenu: params => fetch(`/menu/deleteMenu`, params, {"fullLoading":true,"successTips":true}),
    // 获取当前平台的菜单列表,
    GetMenuListForApp: params => fetch(`/menu/menuListForApp`, params, {}),
    // 获取当前平台的某个角色的菜单列表,
    GetMenuListForAppAndRole: params => fetch(`/menu/menuListForAppAndRole`, params, {}),
    // 保存当前平台的某个角色的菜单列表,
    SetMenuListForAppAndRole: params => fetch(`/menu/saveMenuListForAppAndRole`, params, {"fullLoading":true,"successTips":true}),
    // 保存用户,
    SaveUser: params => fetch(`/user/saveUser`, params, {"fullLoading":true,"successTips":true}),
    // 删除账号,
    DeleteUser: params => fetch(`/user/deleteUser`, params, {"fullLoading":true,"successTips":true}),
    // 获取账号信息,
    GetUser: params => fetch(`/user/getUser`, params, {}),
    // 获取用户列表,
    GetUserAll: params => fetch(`/user/getUserAll`, params, {}),
    // 账户激活,
    SetUserActive: params => fetch(`/user/setUserActive`, params, {"fullLoading":true,"successTips":true}),
    // 账户锁定,
    SetUserLock: params => fetch(`/user/setUserLock`, params, {"fullLoading":true,"successTips":true}),
    // 账户锁定,
    SetUserUnLock: params => fetch(`/user/setUserUnLock`, params, {"fullLoading":true,"successTips":true}),
    // 重置密码,
    ResetPassword: params => fetch(`/user/resetPassword`, params, {"fullLoading":true,"successTips":true}),
    // 获取用户的分组信息,
    GetUserDepts: params => fetch(`/user/getUserDepts`, params, {}),
    // 获取可以给用户设置分组的分组列表,
    GetDeptsForUser: params => fetch(`/user/getDeptsForUser`, params, {}),
    // 设置用户的分组信息,
    SetUserDepts: params => fetch(`/user/setUserDepts`, params, {"fullLoading":true,"successTips":true}),
    // 获取用户的角色信息,
    GetUserRoles: params => fetch(`/user/getUserRoles`, params, {}),
    // 获取可以给用户授权的角色列表,
    GetRolesForUser: params => fetch(`/user/getRolesForUser`, params, {}),
    // 设置用户的分组信息,
    SetUserRoles: params => fetch(`/user/setUserRoles`, params, {"fullLoading":true,"successTips":true}),
    // 修改密码,
    UpdatePassword: params => fetch(`/user/updatePassword`, params, {"fullLoading":true,"successTips":true}),
    // 保存上传的用户文件,
    ImportSaveUser: params => fetch(`/user/importSaveUser`, params, {"fullLoading":true,"successTips":true}),
    // 修改用户的页面布局信息,
    UpdateLayout: params => fetch(`/user/updateLayout`, params, {}),
    // 登录,
    Login: params => fetch(`/login/login`, params, {}),
    // 登出,
    SignOut: params => fetch(`/login/signOut`, params, {}),
    // 获取边界数据,
    GetBoundary: params => fetch(`/base/getBoundary`, params, {}),
    // 获取当前地理位置,
    GetLocation: params => fetch(`/base/getLocation`, params, {}),
    // 查询云图数据,
    GetCloudList: params => fetch(`/base/getCloudList`, params, {}),
    // 查询等值线,
    GetContourList: params => fetch(`/base/getContourList`, params, {}),
    // 获取测站的监控列表,
    GetSiteListMonitor: params => fetch(`/monitorSite/getSiteList`, params, {}),
    // 获取雨情数据,
    GetRainAllMointor: params => fetch(`/monitorRain/getRainAllMointor`, params, {}),
    // 雨情弹框基本信息,
    GetDetailRainInforMonitor: params => fetch(`/monitorRain/getDetailRainInforMonitor`, params, {}),
    // 近7日降雨过程线,
    DaysRainLineMonitor: params => fetch(`/monitorRain/raindayslineMonitor`, params, {}),
    // 时段降雨过程,
    TimeRainLineMonitor: params => fetch(`/monitorRain/raintimelineMonitor`, params, {}),
    // 未来48小时降雨过程,
    FutureRainLineMonitor: params => fetch(`/monitorRain/rainfuturelineMonitor`, params, {}),
    // 获取测站的监控列表,
    GetVideoStationListMonitor: params => fetch(`/monitorVideo/getVideoStationListMonitor`, params, {}),
    // 获取最新河道水情,
    GetNewRiverWaterMonitor: params => fetch(`/monitorWater/river/riversMonitor`, params, {}),
    // 获取最新水库水情,
    GetNewRsvrWaterMonitor: params => fetch(`/monitorWater/rsvr/rsvrsMonitor`, params, {}),
    // 查询水情详情-基本信息,
    WaterDetailMonitor: params => fetch(`/monitorWater/waterDetailMonitor`, params, {}),
    // 查询水情-河道-水位流量过程线,
    RiverflowLineMonitor: params => fetch(`/monitorWater/riverflowLineMonitor`, params, {}),
    // 查询水情-水库-水位流量过程线,
    RsvrFlowLineMonitor: params => fetch(`/monitorWater/rsvrFlowLineMonitor`, params, {}),
    // 查询水情-水库-水位库容曲线,
    RsvrCapacityLineMonitor: params => fetch(`/monitorWater/rsvrCapacityLineMonitor`, params, {}),
    // 获取预警数据,
    GetWarnAllMonitor: params => fetch(`/monitorWarn/getWarnAllMonitor`, params, {}),
    // 获取预警处理数据,
    GetWarnDetailProcessPeopleMonitor: params => fetch(`/monitorWarn/getWarnDetailProcessPeopleMonitor`, params, {}),
    // 预警-督导-处置,
    PostProcessTipsMonitor: params => fetch(`/monitorWarn/postProcessTipsMonitor`, params, {"fullLoading":true,"successTips":true}),
    // 预警-督导-查询状态,
    GetProcessTipsMonitor: params => fetch(`/monitorWarn/getProcessTipsMonitor`, params, {}),
    // 预警处置的立即提示,
    SetProcessTipsMonitor: params => fetch(`/monitorWarn/setProcessTipsMonitor`, params, {"fullLoading":true,"successTips":true}),
    // 小流域空间数据,
    GetWatershedSpatialDataMonitor: params => fetch(`/monitorWarn/getwatershedSpatialDataMonitor`, params, {}),
    // 滚动预警,
    ScrollWarningMonitor: params => fetch(`/monitorWarn/scrollWarningMonitor`, params, {}),
    // 获取工情类别,
    GetWorkTypeAllMonitor: params => fetch(`/monitorWork/getWorkTypeAllMonitor`, params, {}),
    // 获取工情数据,
    GetWorkAllMonitor: params => fetch(`/monitorWork/getWorkAllMonitor`, params, {}),
    // 获取工情详情,
    GetWorkDetailMonitor: params => fetch(`/monitorWork/getWorkDetailMonitor`, params, {}),
    // 获取避险转移的列表,
    GetSafeTransferNum: params => fetch(`/effectRange/getSafeTransferNum`, params, {}),
    // 获取避险转移的列表,
    GetSafeTransferList: params => fetch(`/effectRange/getSafeTransferList`, params, {}),
    // 获取历史山洪灾害的列表,
    GetHisDisasterList: params => fetch(`/effectRange/getHisDisasterList`, params, {}),
    // 获取山洪沟的列表,
    GetMountainList: params => fetch(`/effectRange/getMountainList`, params, {}),
    // 获取面板详情,
    GetRangeDetail: params => fetch(`/effectRange/getRangeDetail`, params, {}),
    // 获取监测站点数据,
    GetMonitoringSiteInfo: params => fetch(`/effectRange/getMonitoringSiteInfo`, params, {})
};