module.exports = [
    {
        pageId: `3a130857-9133-efa7-7f45-e9bc9d1a10d9`,
        pageNm: `综合监视`,
        pageType: `component`,
        url: `/internet_platform/monitor_manage`,
        menuLogo: `icon-monitor`,
        target: `_blank`,
        sortId: 1,
        children: [],
        module: `monitorManage`,
        mustLogin: true,
        layoutId: `Layout-Base`,
        config: `[{"id":"mapControl","components":[{"id":"MapControlsZoom","componentName":"Map-Controls-Zoom","position":"right-top","sort":3},{"id":"MapControlsAim","componentName":"Map-Controls-Aim","position":"right-top","sort":1},{"id":"MapControlsLayer","componentName":"Map-Controls-Layer","position":"right-top","sort":2},{"id":"MapControlsFullScreen","componentName":"Map-Controls-FullScreen","position":"top-right","sort":1},{"id":"MapControlsMeasureArea","componentName":"Map-Controls-MeasureArea","position":"top-right","sort":3},{"id":"MapControlsMeasureDistance","componentName":"Map-Controls-MeasureDistance","position":"top-right","sort":2},{"id":"MapControlsLegend","componentName":"Map-Controls-Legend","position":"right-bottom","sort":2}]},{"id":"mapBusiness","components":[{"id":"MapBusinessMonitorBase","componentName":"Map-Business-MonitorBase","position":"left-bottom","sort":3,"subComponents":[{"id":"MapBusinessMonitorBaseSite","componentName":"Map-Business-MonitorBase-Site","title":"站点","icon":"icon-monitor","sort":1,"subComponents":[{"id":"ChartRainfallProcess","componentName":"Chart-Rainfall-Process","title":"雨情","icon":"icon-monitor","sort":2,"active":true},{"id":"ChartWaterLevelProcess","componentName":"Chart-WaterLevel-Process","title":"雨情","icon":"icon-monitor","sort":2,"active":true},{"id":"ChartWaterLevelSketch","componentName":"Chart-WaterLevel-Sketch","title":"雨情","icon":"icon-monitor","sort":2,"active":true}]},{"id":"MapBusinessMonitorBaseRain","componentName":"Map-Business-MonitorBase-Rain","title":"雨情","icon":"icon-monitor","sort":2,"active":true},{"id":"MapBusinessMonitorBaseWater","componentName":"Map-Business-MonitorBase-Water","title":"水情","icon":"icon-monitor","sort":3},{"id":"MapBusinessMonitorBaseCloud","componentName":"Map-Business-MonitorBase-Cloud","title":"云图","icon":"icon-monitor","sort":4}]}]}]`,
        visible: 1
    },
    {
        pageId: `e7282bc8-b133-efa7-7f45-ec3072233986`,
        pageNm: `预警总览`,
        pageType: `component`,
        url: `/internet_platform/warn_manage`,
        menuLogo: `icon-warn`,
        target: `_blank`,
        sortId: 2,
        children: [],
        module: `warnManage`,
        mustLogin: false,
        layoutId: `Layout-Base`,
        config: `[]`,
        visible: 1
    },
    {
        pageId: `6ac5fd2a-3133-efa7-7f45-e7f834214cfc`,
        pageNm: `分析对比`,
        pageType: `label`,
        url: ``,
        menuLogo: `icon-analysis`,
        target: `_blank`,
        sortId: 3,
        children: [
            {
                pageId: `ad2886dc-1133-efa7-7f45-e799b956d304`,
                pageNm: `雨情查询`,
                pageType: `component`,
                url: `/internet_platform/analysis_manage/rain_manage`,
                menuLogo: `icon-network`,
                target: `_self`,
                sortId: 999,
                children: [],
                module: `rainManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `a0a0f8aa-c133-efa7-7f45-e70152e9d379`,
                pageNm: `水雨情报表`,
                pageType: `component`,
                url: `/internet_platform/analysis_manage/report_manage`,
                menuLogo: `icon-network`,
                target: `_self`,
                sortId: 999,
                children: [],
                module: `reportManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            }
        ],
        module: `analysisManage`,
        mustLogin: false,
        open: 0,
        layoutId: ``,
        config: `""`,
        visible: 1
    },
    {
        pageId: `9091ac29-f133-efa7-7f45-e81be491746d`,
        pageNm: `信息推送`,
        pageType: `label`,
        url: ``,
        menuLogo: `icon-email`,
        target: `_blank`,
        sortId: 4,
        children: [
            {
                pageId: `2c40ce0a-9133-efa7-7f45-e8d592674899`,
                pageNm: `通讯录管理`,
                pageType: `component`,
                url: `/internet_platform/information_manage/address_book_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `addressBookManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `bb63e968-6133-efa7-7f45-e836b49213f2`,
                pageNm: `消息推送`,
                pageType: `component`,
                url: `/internet_platform/information_manage/message_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `messageManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            }
        ],
        module: `informationManage`,
        mustLogin: false,
        open: 0,
        layoutId: ``,
        config: `""`,
        visible: 1
    },
    {
        pageId: `a4a9ac25-2133-efa7-7f45-e9fa299d8b67`,
        pageNm: `平台管理`,
        pageType: `label`,
        url: ``,
        menuLogo: `icon-sys`,
        target: `_blank`,
        sortId: 5,
        children: [
            {
                pageId: `c19a4f20-2133-efa7-7f45-e9c547aee6b6`,
                pageNm: `数据导出`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/data_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `dataManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `d388d299-e133-efa7-7f45-e90e4b05534c`,
                pageNm: `设备管理`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/equipment_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `equipmentManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `d983f37e-2133-efa7-7f45-eab3d50b6489`,
                pageNm: `分组管理`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/group_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `groupManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `4e3c113c-c133-efa7-7f45-eacc1237fcca`,
                pageNm: `角色管理`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/role_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `roleManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `7fcfdbac-8133-efa7-7f45-eaa2771554dc`,
                pageNm: `规则管理`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/rule_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `ruleManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `81f2b9dc-e133-efa7-7f45-ea1afcedc534`,
                pageNm: `测站管理`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/site_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `siteManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `2b66a529-a133-efa7-7f45-eaa8a1dbd62d`,
                pageNm: `用户管理`,
                pageType: `component`,
                url: `/internet_platform/platform_manage/user_manage`,
                menuLogo: `icon-network`,
                target: `_self`,
                sortId: 999,
                children: [],
                module: `userManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            }
        ],
        module: `platformManage`,
        mustLogin: false,
        open: 0,
        layoutId: ``,
        config: `""`,
        visible: 1
    },
    {
        pageId: `980224b0-8133-efa7-7f45-eb053caa6adb`,
        pageNm: `系统管理`,
        pageType: `label`,
        url: ``,
        menuLogo: `icon-sys`,
        target: `_blank`,
        sortId: 6,
        children: [
            {
                pageId: `07783555-a133-efa7-7f45-eb27339d7c8c`,
                pageNm: `图表总览`,
                pageType: `component`,
                url: `/internet_platform/sys_manage/chart_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `chartManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `92f0c56f-f133-efa7-7f45-eba91d8bf893`,
                pageNm: `字体图标`,
                pageType: `component`,
                url: `/internet_platform/sys_manage/icon_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `iconManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `6fb3d1a3-4133-efa7-7f45-ec32b12f98cd`,
                pageNm: `菜单管理`,
                pageType: `component`,
                url: `/internet_platform/sys_manage/menu_manage`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `menuManage`,
                mustLogin: false,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            },
            {
                pageId: `390cc774-3133-efa7-7f45-eca03a64a5c5`,
                pageNm: `webSocket实例`,
                pageType: `component`,
                url: `/internet_platform/sys_manage/web_socket`,
                menuLogo: `icon-network`,
                target: `_blank`,
                sortId: 999,
                children: [],
                module: `webSocket`,
                mustLogin: true,
                layoutId: `Layout-Base`,
                config: `[]`,
                visible: 1
            }
        ],
        module: `sysManage`,
        mustLogin: false,
        open: 0,
        layoutId: ``,
        config: `""`,
        visible: 1
    }
];
