module.exports = [
    {
        "pageId": "67844fa8-7134-13fb-9a7b-5461f8326e54",
        "pageNm": "实时监视",
        "pageType": "component",
        "url": "/vision_list_project/realtime_monitoring",
        "menuLogo": "menu_realtime_monitoring",
        "target": "_single",
        "sortId": 1,
        "children": [],
        "module": "realtimeMonitoring",
        "mustLogin": true,
        "layoutId": "",
        "config": "[{\"id\":\"MapView\",\"center\":[26.595353,106.6602],\"zoom\":8,\"minZoom\":1,\"maxZoom\":18,\"regions\":[{\"id\":\"BaseLayers\",\"title\":\"地图底图\",\"components\":[{\"title\":\"谷歌地图\",\"sort\":2,\"list\":[{\"id\":\"BusinessLayersGoogleVector\",\"componentName\":\"MapBase-GoogleVector\",\"config\":{\"icon\":\"/map/googlemap.png\",\"title\":\"谷歌矢量\",\"sort\":2}},{\"id\":\"BusinessLayersGoogleImage\",\"componentName\":\"MapBase-GoogleImage\",\"config\":{\"icon\":\"/map/googleimage.png\",\"title\":\"谷歌影像\",\"sort\":3}},{\"id\":\"BusinessLayersGoogleTerrain\",\"componentName\":\"MapBase-GoogleTerrain\",\"config\":{\"icon\":\"/map/googletrain.png\",\"title\":\"谷歌地形\",\"sort\":4}}],\"type\":\"google\"},{\"title\":\"天地图地图\",\"sort\":1,\"list\":[{\"id\":\"BusinessLayersTianDiTuVector\",\"componentName\":\"MapBase-TianDiTuVector\",\"config\":{\"icon\":\"/map/tianditumap.png\",\"title\":\"天地图矢量\",\"sort\":5,\"active\":true}},{\"id\":\"BusinessLayersTianDiTuImage\",\"componentName\":\"MapBase-TianDiTuImage\",\"config\":{\"icon\":\"/map/tiandituimage.png\",\"title\":\"天地图影像\",\"sort\":6}},{\"id\":\"BusinessLayersTianDiTuTerrain\",\"componentName\":\"MapBase-TianDiTuTerrain\",\"config\":{\"icon\":\"/map/tianditutrain.png\",\"title\":\"天地图地形\",\"sort\":7}}],\"type\":\"tianditu\"}]},{\"id\":\"BusinessLayers\",\"title\":\"业务图层\",\"components\":[{\"id\":\"BusinessLayersVideoSite\",\"componentName\":\"Map-Business-Layers-VideoSite\",\"config\":{\"code\":\"BusinessLayersVideoSite\",\"layerGroupName\":\"VideoSite\",\"title\":\"视频监视站\",\"icon\":\"Map-Icon-VideoSite\",\"init\":true,\"controllByLayer\":false,\"controllByLegend\":true,\"legendSort\":13,\"subscribeKey\":\"\"}}]},{\"id\":\"Controls\",\"title\":\"控制按钮\",\"components\":[{\"id\":\"MapControlsBaseLayer\",\"componentName\":\"Map-Controls-BaseLayer\",\"config\":{\"position\":\"left-bottom\",\"sort\":4}},{\"id\":\"MapControlsAim\",\"componentName\":\"Map-Controls-Aim\",\"config\":{\"position\":\"left-bottom\",\"sort\":3}},{\"id\":\"MapControlsBusinessLayer\",\"componentName\":\"Map-Controls-BusinessLayer\",\"config\":{\"position\":\"left-bottom\",\"sort\":5}},{\"id\":\"MapControlsZoom\",\"componentName\":\"Map-Controls-Zoom\",\"config\":{\"position\":\"left-bottom\",\"sort\":1}},{\"id\":\"MapControlsBaseLegend\",\"componentName\":\"Map-Controls-Base-Legend\",\"config\":{\"position\":\"left-bottom\",\"sort\":2}},{\"id\":\"MapControlsAttr\",\"componentName\":\"Map-Controls-Attr\",\"config\":{\"position\":\"left-top\",\"sort\":1}},{\"id\":\"MapControlsRegion\",\"componentName\":\"Map-Controls-Region\",\"config\":{\"position\":\"left-top\",\"sort\":2}}]},{\"id\":\"Plugins\",\"title\":\"地图插件\",\"components\":[{\"id\":\"MapPluginsBoundary\",\"componentName\":\"Map-Plugins-Boundary\",\"config\":{\"inside\":{\"color\":\"#9a9a9a\",\"weight\":2}}}]}]},{\"id\":\"MapBusiness\",\"components\":[{\"id\":\"MapBusinessMonitorContainerBase\",\"componentName\":\"Map-Business-Monitor-ContainerBase\",\"config\":{\"position\":\"right\",\"sort\":3},\"subComponents\":[{\"id\":\"MapBusinessMonitorSiteList\",\"componentName\":\"Map-Business-Monitor-Site-List\",\"config\":{\"title\":\"测站列表\",\"icon\":\"icon-monitor\",\"sort\":4}}]}]}]",
        "visible": 1,
        "describe": "",
        "componentName": "RealtimeMonitoring"
    },
    {
        "pageId": "ae72f4c8-8134-13fb-9a7b-537b23d3d6c5",
        "pageNm": "综合分析",
        "pageType": "component",
        "url": "/vision_list_project/comprehensive_analysis",
        "menuLogo": "icon-network",
        "target": "_single",
        "sortId": 999,
        "children": [],
        "module": "visionListProjectComprehensiveAnalysis",
        "mustLogin": true,
        "layoutId": "",
        "config": "[]",
        "visible": 1,
        "describe": "",
        "componentName": "VisionListProjectComprehensiveAnalysis"
    },
    {
        "pageId": "efa9ac13-c134-13fb-9a7b-530260f53d20",
        "pageNm": "字体库",
        "pageType": "component",
        "url": "/font_library",
        "menuLogo": "icon-network",
        "target": "_blank",
        "sortId": 999,
        "children": [],
        "module": "fontLibrary",
        "mustLogin": false,
        "layoutId": "",
        "config": "[]",
        "visible": 1,
        "describe": "",
        "componentName": "FontLibrary"
    },
    {
        "pageId": "e7e1e1db-7134-13fb-9a7b-54e27f1065f8",
        "pageNm": "系统管理",
        "pageType": "label",
        "url": "",
        "menuLogo": "icon-network",
        "target": "_blank",
        "sortId": 999,
        "children": [
            {
                "pageId": "1b4f9261-8134-13fb-9a7b-54e2d3f279c5",
                "pageNm": "用户管理",
                "pageType": "component",
                "url": "/vision_list_project/sys_manage/user_manage",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 1,
                "children": [],
                "module": "userManage",
                "mustLogin": true,
                "layoutId": "",
                "config": "[]",
                "visible": 1,
                "describe": "",
                "componentName": "UserManage"
            },
            {
                "pageId": "3b5616c6-2134-13fb-9a7b-545d59b89f71",
                "pageNm": "分组管理",
                "pageType": "component",
                "url": "/vision_list_project/sys_manage/dept_manage",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 2,
                "children": [],
                "module": "deptManage",
                "mustLogin": true,
                "layoutId": "",
                "config": "[]",
                "visible": 1,
                "describe": "",
                "componentName": "DeptManage"
            },
            {
                "pageId": "0a3fe68d-d134-13fb-9a7b-54371cfd7204",
                "pageNm": "菜单管理",
                "pageType": "component",
                "url": "/vision_list_project/sys_manage/menu_manage",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 3,
                "children": [],
                "module": "menuManage",
                "mustLogin": true,
                "layoutId": "",
                "config": "[]",
                "visible": 1,
                "describe": "",
                "componentName": "MenuManage"
            },
            {
                "pageId": "1a7a60bf-5134-13fb-9a7b-54596f09e64e",
                "pageNm": "角色管理",
                "pageType": "component",
                "url": "/vision_list_project/sys_manage/role_manage",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 4,
                "children": [],
                "module": "roleManage",
                "mustLogin": true,
                "layoutId": "",
                "config": "[]",
                "visible": 1,
                "describe": "",
                "componentName": "RoleManage"
            },
            {
                "pageId": "c39dee5e-e134-13fb-9a7b-54174d12f7b0",
                "pageNm": "角色菜单权限管理",
                "pageType": "component",
                "url": "/vision_list_project/sys_manage/role_menu_authority_manage",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 5,
                "children": [],
                "module": "roleMenuAuthorityManage",
                "mustLogin": true,
                "layoutId": "",
                "config": "[]",
                "visible": 1,
                "describe": "",
                "componentName": "RoleMenuAuthorityManage"
            }
        ],
        "module": "sysManage",
        "mustLogin": false,
        "open": 0,
        "layoutId": "",
        "config": "\"\"",
        "visible": 1,
        "describe": "",
        "componentName": ""
    }
]