module.exports = [
    {
        "pageId": "8800c72f-3133-f00d-7361-fbfccbb3433d",
        "pageNm": "基础信息",
        "pageType": "label",
        "url": "",
        "menuLogo": "menu_basic_information",
        "target": "_single",
        "sortId": 9,
        "children": [
            {
                "pageId": "c6a74c13-1133-f00a-a8a4-5bb2542b8d49",
                "pageNm": "县乡村基本信息",
                "pageType": "component",
                "url": "/internet_platform/basic_information/administrative_region/county_country_information",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 1,
                "children": [],
                "module": "countyCountryInformation",
                "mustLogin": true,
                "layoutId": "Layout-Base",
                "config": "[]",
                "visible": 1
            },
            {
                "pageId": "8cd7690d-7133-f00a-a8a4-5bb7c3da3515",
                "pageNm": "县乡村预案",
                "pageType": "component",
                "url": "/internet_platform/basic_information/administrative_region/county_country_reserve_plan",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 2,
                "children": [],
                "module": "countyCountryReservePlan",
                "mustLogin": true,
                "layoutId": "Layout-Base",
                "config": "[]",
                "visible": 1
            },
            {
                "pageId": "c80438b0-8133-f00a-a8a4-5d4b3042bc74",
                "pageNm": "小流域信息",
                "pageType": "label",
                "url": "",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 2,
                "children": [
                    {
                        "pageId": "339f311c-7133-f00a-a8a4-5d206353217b",
                        "pageNm": "小流域信息",
                        "pageType": "component",
                        "url": "/internet_platform/basic_information/small_watershed/small_watershed_basic_information",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 1,
                        "children": [],
                        "module": "smallWatershedBasicInformation",
                        "mustLogin": true,
                        "layoutId": "Layout-Base",
                        "config": "[]",
                        "visible": 1
                    }
                ],
                "module": "smallWatershed",
                "mustLogin": false,
                "open": 0,
                "layoutId": "",
                "config": "\"\"",
                "visible": 1
            },
            {
                "pageId": "a164c4e1-f133-f00a-a8a4-5b21441e149c",
                "pageNm": "山洪灾害影响情况",
                "pageType": "component",
                "url": "/internet_platform/basic_information/administrative_region/mountain_flood_disaster",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 3,
                "children": [],
                "module": "mountainFloodDisaster",
                "mustLogin": true,
                "layoutId": "Layout-Base",
                "config": "[]",
                "visible": 1
            },
            {
                "pageId": "18ea583b-3133-f00a-a8a4-5df728c9d346",
                "pageNm": "测站基本信息",
                "pageType": "label",
                "url": "",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 3,
                "children": [
                    {
                        "pageId": "15f29d21-7133-f00a-a8a4-5d2c185a4961",
                        "pageNm": "测站基本信息",
                        "pageType": "component",
                        "url": "/internet_platform/basic_information/station_information/station_basic_information",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 1,
                        "children": [],
                        "module": "stationBasicInformation",
                        "mustLogin": true,
                        "layoutId": "Layout-Base",
                        "config": "[]",
                        "visible": 1
                    }
                ],
                "module": "stationInformation",
                "mustLogin": false,
                "open": 0,
                "layoutId": "",
                "config": "\"\"",
                "visible": 1
            },
            {
                "pageId": "bf8530cd-4133-f00a-a8a4-5d6f03058a0d",
                "pageNm": "工情信息",
                "pageType": "label",
                "url": "",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 4,
                "children": [
                    {
                        "pageId": "0735de26-8133-f00a-a8a4-5d6faaa342e0",
                        "pageNm": "水库信息",
                        "pageType": "component",
                        "url": "/internet_platform/basic_information/work_situation/reservoir_information",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 1,
                        "children": [],
                        "module": "reservoirInformation",
                        "mustLogin": true,
                        "layoutId": "Layout-Base",
                        "config": "[]",
                        "visible": 1
                    },
                    {
                        "pageId": "8d6c6022-a133-f00a-a8a4-5d26c4f6e9a1",
                        "pageNm": "水情信息",
                        "pageType": "component",
                        "url": "/internet_platform/basic_information/work_situation/river_information",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 2,
                        "children": [],
                        "module": "riverInformation",
                        "mustLogin": true,
                        "layoutId": "Layout-Base",
                        "config": "[]",
                        "visible": 1
                    },
                    {
                        "pageId": "7e0e707d-6133-f00a-a8a4-5d2eb68f1672",
                        "pageNm": "堤防信息",
                        "pageType": "component",
                        "url": "/internet_platform/basic_information/work_situation/dam_information",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 3,
                        "children": [],
                        "module": "damInformation",
                        "mustLogin": true,
                        "layoutId": "Layout-Base",
                        "config": "[]",
                        "visible": 1
                    }
                ],
                "module": "workSituation",
                "mustLogin": false,
                "open": 0,
                "layoutId": "",
                "config": "\"\"",
                "visible": 1
            },
            {
                "pageId": "fa14dbb9-c133-f00a-a8a4-5bda822f875e",
                "pageNm": "灾情信息",
                "pageType": "label",
                "url": "",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 5,
                "children": [
                    {
                        "pageId": "3e627a07-2133-f00a-a8a4-5b026d6e96fc",
                        "pageNm": "历史灾情",
                        "pageType": "component",
                        "url": "/internet_platform/basic_information/disaster_situation/history_disaster",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 999,
                        "children": [],
                        "module": "historyDisaster",
                        "mustLogin": true,
                        "layoutId": "Layout-Base",
                        "config": "[]",
                        "visible": 1
                    }
                ],
                "module": "disasterSituation",
                "mustLogin": false,
                "open": 0,
                "layoutId": "",
                "config": "\"\"",
                "visible": 1
            },
            {
                "pageId": "402ee4b0-f133-f00a-a8a4-5bf83feea512",
                "pageNm": "调查评价",
                "pageType": "label",
                "url": "",
                "menuLogo": "icon-network",
                "target": "_single",
                "sortId": 6,
                "children": [
                    {
                        "pageId": "811370c9-e133-f00a-a8a4-5ba18bd62fb6",
                        "pageNm": "水文气象",
                        "pageType": "label",
                        "url": "",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 1,
                        "children": [],
                        "module": "hydrologyMeteorological",
                        "mustLogin": false,
                        "open": 0,
                        "layoutId": "",
                        "config": "\"\"",
                        "visible": 1
                    },
                    {
                        "pageId": "2292ce66-7133-f00a-a8a4-5bcaf2a537b4",
                        "pageNm": "分析评价成果",
                        "pageType": "label",
                        "url": "",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 2,
                        "children": [],
                        "module": "AnalysisAchievements",
                        "mustLogin": false,
                        "open": 0,
                        "layoutId": "",
                        "config": "\"\"",
                        "visible": 1
                    },
                    {
                        "pageId": "88f055f5-3133-f00a-a8a4-5d0719256af6",
                        "pageNm": "断面测量成果类",
                        "pageType": "label",
                        "url": "",
                        "menuLogo": "icon-network",
                        "target": "_single",
                        "sortId": 3,
                        "children": [],
                        "module": "sectionMeasurementResults",
                        "mustLogin": false,
                        "open": 0,
                        "layoutId": "",
                        "config": "\"\"",
                        "visible": 1
                    },
                    {
                        "pageId": "b24cb4fc-4133-f00b-7fc7-1396ee1ab19e",
                        "pageNm": "现场调查成果类",
                        "pageType": "label",
                        "url": "",
                        "menuLogo": "icon-network",
                        "target": "_blank",
                        "sortId": 999,
                        "children": [],
                        "module": "fieldInvestigationResults",
                        "mustLogin": false,
                        "open": 0,
                        "layoutId": "",
                        "config": "\"\"",
                        "visible": 1
                    }
                ],
                "module": "investigationEvaluate",
                "mustLogin": false,
                "open": 0,
                "layoutId": "",
                "config": "\"\"",
                "visible": 1
            }
        ],
        "module": "basicInformation",
        "mustLogin": false,
        "open": 0,
        "layoutId": "",
        "config": "\"\"",
        "visible": 1
    }
]