import fetch from '@rich/richwayweb-components/src/pc/utils/fetch';

export default {
    // undefined,
    GetBaseConfig: params => fetch(`/base/getBaseConfig`, params, {}),
    // undefined,
    GetProvinceData: params => fetch(`/base/getProvinceData`, params, {"cache":true}),
    // undefined,
    GetSubRegionData: params => fetch(`/base/getSubRegionData`, params, {}),
    // undefined,
    GetRegionData: params => fetch(`/base/getRegionData`, params, {}),
    // undefined,
    GetAdcdCity: params => fetch(`/base/waring/adcdCity`, params, {}),
    // undefined,
    GetGeographicInfo: params => fetch(`/base/getGeographicInfo`, params, {}),
    // undefined,
    GetAppAll: params => fetch(`/app/appAll`, params, {}),
    // undefined,
    SaveUser: params => fetch(`/user/saveUser`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    DeleteUser: params => fetch(`/user/deleteUser`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    GetUser: params => fetch(`/user/getUser`, params, {}),
    // undefined,
    GetUserAll: params => fetch(`/user/getUserAll`, params, {}),
    // undefined,
    SetUserActive: params => fetch(`/user/setUserActive`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    SetUserLock: params => fetch(`/user/setUserLock`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    SetUserUnLock: params => fetch(`/user/setUserUnLock`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    ResetPassword: params => fetch(`/user/resetPassword`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    GetUserDepts: params => fetch(`/user/getUserDepts`, params, {}),
    // undefined,
    GetDeptsForUser: params => fetch(`/user/getDeptsForUser`, params, {}),
    // undefined,
    SetUserDepts: params => fetch(`/user/setUserDepts`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    GetUserRoles: params => fetch(`/user/getUserRoles`, params, {}),
    // undefined,
    GetRolesForUser: params => fetch(`/user/getRolesForUser`, params, {}),
    // undefined,
    SetUserRoles: params => fetch(`/user/setUserRoles`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    UpdatePassword: params => fetch(`/user/updatePassword`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    ImportSaveUser: params => fetch(`/user/importSaveUser`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    UpdateLayout: params => fetch(`/user/updateLayout`, params, {}),
    // undefined,
    Login: params => fetch(`/login/login`, params, {}),
    // undefined,
    SignOut: params => fetch(`/login/signOut`, params, {}),
    // undefined,
    GetMenuListForUser: params => fetch(`/menu/menuListForUser`, params, {}),
    // undefined,
    GetMenuListForAvailable: params => fetch(`/menu/menuLForAvailable`, params, {}),
    // undefined,
    GetMenuInfo: params => fetch(`/menu/menuInfo`, params, {}),
    // undefined,
    SaveMenu: params => fetch(`/menu/saveMenu`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    DeleteMenu: params => fetch(`/menu/deleteMenu`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    GetMenuListForApp: params => fetch(`/menu/menuListForApp`, params, {}),
    // undefined,
    GetMenuListForAppAndRole: params => fetch(`/menu/menuListForAppAndRole`, params, {}),
    // undefined,
    SetMenuListForAppAndRole: params => fetch(`/menu/saveMenuListForAppAndRole`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    GetDeptList: params => fetch(`/dept/deptList`, params, {}),
    // undefined,
    SaveDept: params => fetch(`/dept/saveDept`, params, {}),
    // undefined,
    DeleteDept: params => fetch(`/dept/deleteDept`, params, {}),
    // undefined,
    GetRoleList: params => fetch(`/role/roleList`, params, {}),
    // undefined,
    SaveRole: params => fetch(`/role/saveRole`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    DeleteRole: params => fetch(`/role/deleteRole`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    GetRoleFilter: params => fetch(`/role/getRoleFilter`, params, {}),
    // undefined,
    SetRoleFilter: params => fetch(`/role/setRoleFilter`, params, {"fullLoading":true,"successTips":true}),
    // undefined,
    ImportSaveRole: params => fetch(`/role/importSaveRole`, params, {"fullLoading":true,"successTips":true})
};